---
- name: Install packages for installation
  package:
    name: "{{ wpcli_dep_packages }}"
    state: present
  tags:
    - packages

- name: Install WP-CLI
  ansible.builtin.get_url:
    url: "{{ wpcli_url }}"
    dest: "{{ wpcli_executable }}"
    mode: 0755
    checksum: "{{ wpcli_checksum }}"
    group: root
    owner: root

- name: Create bash-completion folder if it doesn't exist
  file:
    path: /etc/bash_completion.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install WP-CLI Bash Completion
  ansible.builtin.get_url:
    url: "{{ wpcli_bash_url }}"
    dest: "{{ wpcli_bash_executable }}"
    mode: 0644
    checksum: "{{ wpcli_bash_checksum }}"
    group: root
    owner: root
