---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (on Redhat).
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install CA-Certificates
      package:
        name: ca-certificates
        state: present

    - name: Install bash-completion
      package:
        name: bash-completion
        state: present

  tasks:
    - name: Remove files
      file:
        name:
          - /usr/local/bin/wp
          - /etc/bash_completion.d/wp_local
        state: absent
