---
name: Release to Ansible Galaxy

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  ansible-galaxy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.3.8
        with:
          api_key: ${{ secrets.galaxy_api_key }}
