---
name: Ansible Role - CI

on:
  pull_request:
  schedule:
    - cron: '3 8 21 * *'

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Molecule tests
        run: tox
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

